-- AlterTable
ALTER TABLE "users" ADD COLUMN     "bio" TEXT;

-- CreateTable
CREATE TABLE "friendships" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "requester_id" UUID NOT NULL,
    "addressee_id" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "friendships_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idx_friendships_addressee" ON "friendships"("addressee_id", "status");

-- CreateIndex
CREATE INDEX "idx_friendships_requester" ON "friendships"("requester_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "friendships_requester_id_addressee_id_key" ON "friendships"("requester_id", "addressee_id");

-- AddForeignKey
ALTER TABLE "friendships" ADD CONSTRAINT "friendships_requester_id_fkey" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "friendships" ADD CONSTRAINT "friendships_addressee_id_fkey" FOREIGN KEY ("addressee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================================
-- Hand-written SQL below this line.
--
-- Everything above this point was generated by `prisma migrate diff` from
-- prisma/schema.prisma. CHECK constraints and triggers have no representation
-- in the Prisma Schema Language, so they're added here by hand — see the
-- comment at the top of schema.prisma for the full explanation.
-- ============================================================================

-- ---------- CHECK constraints ----------

ALTER TABLE "friendships" ADD CONSTRAINT "status_valid" CHECK (
  status IN ('pending', 'accepted', 'declined')
);
ALTER TABLE "friendships" ADD CONSTRAINT "not_self" CHECK (requester_id <> addressee_id);

-- ---------- updated_at trigger ----------
-- Reuses set_updated_at(), already defined by the _init migration.

CREATE TRIGGER friendships_updated_at BEFORE UPDATE ON "friendships"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
